#!/usr/bin/env python3
"""Apply the 4 Oct decision rule: does HiDeF replace THEMA as the engine?

**The rule was declared in `DECISIONS.md` before anything was built**, and this applies it exactly
as written. Nothing here is tuned, and no alternative statistic is substituted.

> Primary metric: specificity AUROC (smallest shared theme size, siblings vs random pairs).
> Reactome siblings and GO siblings separately, at zero gene overlap and with all bands pooled --
> four cells. Paired bootstrap over pairs, 2,000 resamples, seed 0; report the 95% CI of
> (HiDeF - THEMA) per cell. If THEMA is not significantly better in ANY of the four cells (every CI
> includes or exceeds 0), and HiDeF's test-4 zero-gene sibling recovery is within 2 points of
> THEMA's on both hierarchies, HiDeF is "at least as good" and we switch engines. Otherwise THEMA
> stays and HiDeF is reported as a baseline.

**The bootstrap resamples the CURATED PAIRS, not the null.** The null is the fixed reference both
arms are scored against; resampling it would measure the stability of the reference rather than of
the comparison. Both arms are scored on the SAME resampled pairs in each replicate, which is what
makes it paired and what makes the difference's interval narrower than either arm's alone.

Usage::

    uv run scripts/hidef_decision.py
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path

import numpy as np

from thema.data.formats import parse_obo_terms
from thema.data.hierarchy import read_reactome_relation
from thema.data.pathways import PathwayCollection
from thema.evaluation import go_parents, jaccard, restrict, sibling_pairs
from thema.ontology.universe import load_embedded

csv.field_size_limit(1 << 30)

NULL_DRAWS = 600_000
NULL_SEED = 20261003

#: Declared in the rule: 2,000 resamples, seed 0.
BOOTSTRAP = 2_000
BOOTSTRAP_SEED = 0

#: Declared in the rule: HiDeF must be within this many points of THEMA on test-4 recovery.
RECOVERY_TOLERANCE = 0.02

#: Practical-equivalence margin on AUROC, declared in the 5 Oct brief. A cell whose CI lies wholly
#: inside +/- this is "equivalent" rather than a win for either arm.
EQUIVALENCE_MARGIN = 0.02


def _parent_of(
    relation: dict[str, list[str]] | dict[str, tuple[str, ...]],
    prefix: str,
    left: list[str],
    right: list[str],
) -> list[str]:
    """The smallest curated parent shared by each pair, as the cluster label.

    Pairs generated by one sibling group share pathways and are not independent observations, so the
    bootstrap has to resample GROUPS. Attributing a pair to the SMALLEST shared parent puts it in
    exactly one cluster and in the tightest group that could have produced it.

    Args:
        relation: Child to parents, in the curated hierarchy.
        prefix: Key prefix, e.g. ``reactome:``.
        left: First members.
        right: Second members.

    Returns:
        One parent label per pair; the pair's own key-pair when no shared parent is found.
    """
    children: dict[str, set[str]] = defaultdict(set)
    for child, parents in relation.items():
        for parent in parents:
            children[parent].add(prefix + child)
    out = []
    for a, b in zip(left, right, strict=True):
        shared = [(len(kids), node) for node, kids in children.items() if a in kids and b in kids]
        out.append(min(shared)[1] if shared else f"{a}|{b}")
    return out


def read_arm(directory: Path) -> tuple[dict[str, frozenset[str]], dict[str, int]]:
    """Pathway homes and theme sizes for one arm.

    Args:
        directory: A build directory in THEMA's schema.

    Returns:
        Pathway key to its themes, and theme to member count.
    """
    members: dict[str, set[str]] = defaultdict(set)
    with (directory / "members.tsv").open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle, delimiter="\t"):
            members[row["node"]].add(row["key"])
    homes: dict[str, set[str]] = defaultdict(set)
    for node, keys in members.items():
        for key in keys:
            homes[key].add(node)
    return ({k: frozenset(v) for k, v in homes.items()},
            {n: len(v) for n, v in members.items()})


def specificity(
    homes: dict[str, frozenset[str]], sizes: dict[str, int],
    left: list[str], right: list[str],
) -> np.ndarray:
    """Smallest shared theme size per pair, inf when none.

    Args:
        homes: Pathway key to its themes.
        sizes: Theme to member count.
        left: First members.
        right: Second members.

    Returns:
        One value per pair.
    """
    out = np.empty(len(left))
    empty: frozenset[str] = frozenset()
    for i, (a, b) in enumerate(zip(left, right, strict=True)):
        shared = homes.get(a, empty) & homes.get(b, empty)
        out[i] = min((sizes[t] for t in shared), default=float("inf"))
    return out


def auroc_from_ranks(curated: np.ndarray, reference_sorted: np.ndarray) -> float:
    """AUROC of curated against a FIXED reference, ties half.

    Uses searchsorted against the pre-sorted reference, so a bootstrap replicate costs
    ``O(n log m)`` instead of re-ranking the whole combined sample. Exactly equals the midrank
    formulation: for each curated value, the count of reference values strictly greater plus half
    the count equal.

    Args:
        curated: Curated-pair values.
        reference_sorted: The null's values, sorted ascending.

    Returns:
        The AUROC.
    """
    m = len(reference_sorted)
    if not len(curated) or not m:
        return float("nan")
    lower = np.searchsorted(reference_sorted, curated, side="left")
    upper = np.searchsorted(reference_sorted, curated, side="right")
    greater = m - upper
    equal = upper - lower
    return float((greater + 0.5 * equal).sum() / (len(curated) * m))


def main(argv: list[str] | None = None) -> int:
    """Apply the rule and print the verdict.

    Args:
        argv: Command-line arguments.

    Returns:
        Process exit status.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=Path("data"))
    parser.add_argument("--version", default="0.3")
    parser.add_argument("--thema", default="recurrent_dag_10770")
    parser.add_argument("--hidef", default="hidef_10770_k15")
    parser.add_argument("--bootstrap", choices=("pair", "cluster"), default="pair",
                        help="'cluster' resamples CURATED PARENTS (sibling groups) rather than "
                             "pairs. Pairs inside one parent share pathways and are not "
                             "independent, so a pair bootstrap understates the uncertainty")
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args(argv)

    root = args.data / "ontology" / f"v{args.version}"
    keys = list(load_embedded(root, args.data / "pathways.tsv").keys)
    present = set(keys)
    collection = PathwayCollection.from_tsv_text(
        (args.data / "pathways.tsv").read_text(encoding="utf-8")
    )
    by_key = {p.key: p for p in collection.pathways if p.key in present}
    arms = {"THEMA": read_arm(root / args.thema), "HiDeF": read_arm(root / args.hidef)}
    print("THE 4 OCT DECISION RULE, applied exactly as declared")
    print(f"  THEMA {args.thema}: {len(arms['THEMA'][1]):,} themes")
    print(f"  HiDeF {args.hidef}: {len(arms['HiDeF'][1]):,} themes")

    rng = np.random.default_rng(NULL_SEED)
    ia = rng.integers(0, len(keys), size=NULL_DRAWS)
    ib = rng.integers(0, len(keys), size=NULL_DRAWS)
    keep = ia != ib
    ia, ib = ia[keep], ib[keep]
    null_left = [keys[i] for i in ia]
    null_right = [keys[j] for j in ib]
    gene_null = np.array([
        (lambda v: -1.0 if v is None else v)(jaccard(by_key[a], by_key[b]))
        for a, b in zip(null_left, null_right, strict=True)
    ])
    zero_null = gene_null == 0.0
    print(f"  null {len(ia):,} pairs; {int(zero_null.sum()):,} at exactly zero gene overlap")
    null_spec = {name: specificity(*arm, null_left, null_right) for name, arm in arms.items()}

    raw = args.data / "raw"
    relation = read_reactome_relation(
        (raw / "ReactomePathwaysRelation.txt").read_text(encoding="utf-8").splitlines()
    )
    terms = parse_obo_terms((raw / "go-basic.obo").read_text(encoding="utf-8").splitlines())
    go_rel = go_parents(terms)
    sources = {
        "Reactome siblings": (sibling_pairs(relation, "reactome:", "reactome-siblings", ""),
                              relation, "reactome:"),
        "GO siblings": (sibling_pairs(go_rel, "go:", "go-siblings", ""), go_rel, "go:"),
    }

    cells: list[dict] = []
    recovery: dict[str, dict[str, float]] = {}
    for label, (source, relation_map, prefix) in sources.items():
        kept = restrict(source, present)
        left = [a for a, _ in kept.pairs]
        right = [b for _, b in kept.pairs]
        gvals = np.array([(lambda v: -1.0 if v is None else v)(
            jaccard(by_key[a], by_key[b])) for a, b in zip(left, right, strict=True)])
        zero = gvals == 0.0
        spec = {name: specificity(*arm, left, right) for name, arm in arms.items()}

        # Test 4 recovery at zero gene overlap: the share of pairs sharing at least one theme.
        recovery[label] = {
            name: float(np.isfinite(spec[name][zero]).mean()) for name in arms
        }
        print(f"\n  {label}: {len(left):,} pairs, {int(zero.sum()):,} at zero gene overlap")
        print(f"    test-4 zero-gene recovery  THEMA {recovery[label]['THEMA']:.1%}  "
              f"HiDeF {recovery[label]['HiDeF']:.1%}  "
              f"difference {recovery[label]['HiDeF'] - recovery[label]['THEMA']:+.1%}")

        # Which curated parent each pair came from, for the cluster bootstrap. A pair can sit under
        # several shared parents; the SMALLEST is used, so a pair is attributed to the tightest
        # group that generated it and each pair belongs to exactly one cluster.
        groups = _parent_of(relation_map, prefix, left, right)

        for band_name, mask, nmask in (
            ("zero gene overlap", zero, zero_null),
            ("all bands pooled", np.ones(len(left), dtype=bool), np.ones(len(ia), dtype=bool)),
        ):
            reference = {name: np.sort(null_spec[name][nmask]) for name in arms}
            point = {name: auroc_from_ranks(spec[name][mask], reference[name]) for name in arms}
            index = np.flatnonzero(mask)
            boot = np.random.default_rng(BOOTSTRAP_SEED)
            diffs = np.empty(BOOTSTRAP)
            if args.bootstrap == "cluster":
                # Resample PARENTS with replacement and take every pair of each drawn parent.
                buckets: dict[str, list[int]] = defaultdict(list)
                for i in index:
                    buckets[groups[i]].append(i)
                names_list = list(buckets)
                members_list = [np.array(buckets[k], dtype=np.int64) for k in names_list]
                for r in range(BOOTSTRAP):
                    drawn = boot.integers(0, len(names_list), size=len(names_list))
                    picked = np.concatenate([members_list[d] for d in drawn])
                    diffs[r] = (auroc_from_ranks(spec["HiDeF"][picked], reference["HiDeF"])
                                - auroc_from_ranks(spec["THEMA"][picked], reference["THEMA"]))
            else:
                for r in range(BOOTSTRAP):
                    picked = index[boot.integers(0, len(index), size=len(index))]
                    diffs[r] = (auroc_from_ranks(spec["HiDeF"][picked], reference["HiDeF"])
                                - auroc_from_ranks(spec["THEMA"][picked], reference["THEMA"]))
            low, high = float(np.percentile(diffs, 2.5)), float(np.percentile(diffs, 97.5))
            thema_better = high < 0.0
            # The practical-equivalence reading, declared in the 5 Oct brief.
            if low >= -EQUIVALENCE_MARGIN and high <= EQUIVALENCE_MARGIN:
                reading = "equivalent"
            elif high < 0.0:
                reading = "THEMA better"
            elif low > 0.0:
                reading = "HiDeF better"
            else:
                reading = "inconclusive"
            cells.append({
                "source": label, "band": band_name, "n": int(mask.sum()),
                "n_null": int(nmask.sum()),
                "auroc_thema": round(point["THEMA"], 4),
                "auroc_hidef": round(point["HiDeF"], 4),
                "difference": round(point["HiDeF"] - point["THEMA"], 4),
                "ci_low": round(low, 4), "ci_high": round(high, 4),
                "thema_significantly_better": thema_better,
                "bootstrap": args.bootstrap,
                "n_clusters": int(len({groups[i] for i in index})),
                "reading_vs_margin": reading,
            })
            print(f"    {band_name:<18} n={int(mask.sum()):>6}  THEMA {point['THEMA']:.4f}  "
                  f"HiDeF {point['HiDeF']:.4f}  diff {point['HiDeF'] - point['THEMA']:+.4f}  "
                  f"95% CI [{low:+.4f}, {high:+.4f}]  "
                  f"{reading.upper():<14} "
                  f"({len({groups[i] for i in index}):,} parents)")

    # ---- the rule ----
    better = [c for c in cells if c["thema_significantly_better"]]
    within = {
        label: recovery[label]["HiDeF"] >= recovery[label]["THEMA"] - RECOVERY_TOLERANCE
        for label in recovery
    }
    switch = (not better) and all(within.values())
    print(f"\n{'=' * 96}")
    print(f"  cells where THEMA is significantly better: {len(better)} of {len(cells)}"
          + (f" -- {', '.join(c['source'] + ', ' + c['band'] for c in better)}" if better else ""))
    for label, ok in within.items():
        print(f"  HiDeF within {RECOVERY_TOLERANCE:.0%} on {label}: {ok} "
              f"({recovery[label]['HiDeF'] - recovery[label]['THEMA']:+.1%})")
    print("\n  VERDICT UNDER THE DECLARED RULE: "
          + ("SWITCH ENGINES to HiDeF" if switch
             else "THEMA STAYS; HiDeF and CliXO are reported as baselines"))
    print("=" * 96)

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps({
            "rule": "DECISIONS.md, 4 Oct, declared before any build",
            "bootstrap": BOOTSTRAP, "bootstrap_seed": BOOTSTRAP_SEED,
            "recovery_tolerance": RECOVERY_TOLERANCE,
            "null_draws": int(len(ia)), "null_seed": NULL_SEED,
            "thema": args.thema, "hidef": args.hidef,
            "cells": cells, "test4_zero_gene_recovery": recovery,
            "cells_thema_significantly_better": len(better),
            "hidef_within_tolerance": within,
            "declared_configuration": bool(args.hidef == "hidef_10770_k15"
                                           and args.bootstrap == "pair"),
            "verdict": (("switch to HiDeF" if switch else "THEMA stays")
                        if (args.hidef == "hidef_10770_k15" and args.bootstrap == "pair")
                        else None),
            "mechanical_reading_only": None if (args.hidef == "hidef_10770_k15"
                                                and args.bootstrap == "pair")
            else ("conditions met" if switch else "conditions not met"),
        }, indent=2) + "\n", encoding="utf-8")
        print(f"\n  -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
